// @flow
export const FETCH_USERS_STARTED = 'users/FETCH_USERS_STARTED';
export const FETCH_USERS_SUCCEEDED = 'users/FETCH_USERS_SUCCEEDED';
export const FETCH_USERS_FAILED = 'users/FETCH_USERS_FAILED';

export const FETCH_USER_STARTED = 'user/FETCH_USER_STARTED';
export const FETCH_USER_SUCCEEDED = 'user/FETCH_USER_SUCCEEDED';
export const FETCH_USER_FAILED = 'user/FETCH_USER_FAILED';
